name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Use v2 instead of v3
      - name: Build the Docker image
        run: docker build -t my-image-name:$(date +%s) -f "Vijay Raghul/Dockerfile" .
